version: "3.8"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2020:5000"
    networks:
      - overlay
    # Uncomment the following lines if you want to deploy the webapp as replicas
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip

  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
    # volumes:
    #   - db_data:/var/lib/redis
    networks:
      - overlay
    # Uncomment the following lines if you want to deploy the Redis database as replicas
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr

# # Uncomment the following lines if you have a volume for the database
# volumes:
#   db-data:

networks:
  overlay:
